FROM badwolf/centos7-ng-fis:1.10
COPY ./fis-parser-tomd /usr/lib/node_modules/fis/node_modules/fis-parser-tomd
COPY ./fis-prepackager-app /usr/lib/node_modules/fis/node_modules/fis-prepackager-app
COPY ./fis-postpackager-increment /usr/lib/node_modules/fis/node_modules/fis-postpackager-increment